kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-controller
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
  storageClassName: "standard-rwo"
