---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-https-jks
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-controller
type: Opaque
data:
  jenkins-jks-pass: {{ .Values.keyStorePass | b64enc }}
  jenkins-jks-file: {{ .Values.keyStoreFile }}

---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-controller
type: Opaque
data:
  jenkins-admin-user: {{ .Values.adminUser | b64enc | quote }}
  jenkins-admin-password: {{ .Values.adminPassword | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: gcp-registry
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: jenkins-controller
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry_key }}

